/* Generated By:JJTree: Do not edit this line. ASTBranchingExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTBranchingExpression extends SimpleNode {
  public ASTBranchingExpression(int id) {
    super(id);
  }

  public ASTBranchingExpression(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=10a85f9fbfdcd88f828202d119196c05 (do not edit this line) */
