/* Generated By:JJTree: Do not edit this line. ASTCompoundStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public class ASTCompoundStatement extends SimpleNode {
    public ASTCompoundStatement(int id) {
        super(id);
    }

    public ASTCompoundStatement(CParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=8bc54104e06bcaef1f7c0d5a5693dc20 (do not edit this line) */
