/* Generated By:JJTree: Do not edit this line. ASTCaseStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTCaseStatement extends SimpleNode {
  public ASTCaseStatement(int id) {
    super(id);
  }

  public ASTCaseStatement(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=4d62186a0a79f723d57d2d6d3aed44be (do not edit this line) */
