/* Generated By:JJTree: Do not edit this line. ASTDirectAbstractDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public class ASTDirectAbstractDeclarator extends SimpleNode {
    public ASTDirectAbstractDeclarator(int id) {
        super(id);
    }

    public ASTDirectAbstractDeclarator(CParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=1c908a1a40d6f549c1d0cd6061d1fee1 (do not edit this line) */
