/* Generated By:JJTree: Do not edit this line. ASTExclusiveORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTExclusiveORExpression extends SimpleNode {
  public ASTExclusiveORExpression(int id) {
    super(id);
  }

  public ASTExclusiveORExpression(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=ad7a118c543fb362d62f6c8fc69d4633 (do not edit this line) */
