/* Generated By:JJTree: Do not edit this line. ASTEnumeratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTEnumeratorList extends SimpleNode {
  public ASTEnumeratorList(int id) {
    super(id);
  }

  public ASTEnumeratorList(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=70a57ce5baf2934eb4df06036343b0fc (do not edit this line) */
