/* Generated By:JJTree: Do not edit this line. ASTExpressionStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class ASTExpressionStatement extends SimpleNode {

    public ASTExpressionStatement(int id) {
        super(id);
    }

    public ASTExpressionStatement(CParser p, int id) {
        super(p, id);
    }

    public boolean isExit() {
        String code = getCode();
        Pattern pattern = Pattern.compile("exit\\([0-9]*\\);");
        Matcher matcher = pattern.matcher(code);
        return matcher.matches();
    }

    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=0eebed5f4a0bd69619cf0a21ba88c1b4 (do not edit this line) */
