/* Generated By:JJTree: Do not edit this line. ASTExternalDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public class ASTExternalDeclaration extends SimpleNode {
    public ASTExternalDeclaration(int id) {
        super(id);
    }

    public ASTExternalDeclaration(CParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=ad62083165c28c615c3b04f5ee80aac4 (do not edit this line) */
