/* Generated By:JJTree: Do not edit this line. ASTEnumerator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTEnumerator extends SimpleNode {
  public ASTEnumerator(int id) {
    super(id);
  }

  public ASTEnumerator(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=caafc30b7725d41adfb0c651df2f61f7 (do not edit this line) */
