/* Generated By:JJTree: Do not edit this line. ASTGotoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;


public
class ASTGotoStatement extends SimpleNode {
	public String getLabel() {
		return jjtGetFirstToken().next.image;
	}

  public ASTGotoStatement(int id) {
    super(id);
  }

  public ASTGotoStatement(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=61b917ec39403dd28769705e8cb9c6c7 (do not edit this line) */
