/* Generated By:JJTree: Do not edit this line. ASTInitDeclaratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTInitDeclaratorList extends SimpleNode {
  public ASTInitDeclaratorList(int id) {
    super(id);
  }

  public ASTInitDeclaratorList(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=e11585c50af2e51bdfafbde2d8c4fc6f (do not edit this line) */
