/* Generated By:JJTree: Do not edit this line. ASTIdentifierStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;


public class ASTIdentifierStatement extends SimpleNode {
    public ASTIdentifierStatement(int id) {
        super(id);
    }

    public ASTIdentifierStatement(CParser p, int id) {
        super(p, id);
    }

    public String getLabel() {
        return jjtGetFirstToken().image;
    }

    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=372ed508d7f8e2a4d76a2733d41d9121 (do not edit this line) */
