/* Generated By:JJTree: Do not edit this line. ASTLogicalORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public class ASTLogicalORExpression extends SimpleNode {
    public ASTLogicalORExpression(int id) {
        super(id);
    }

    public ASTLogicalORExpression(CParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=7deb59d665c0ca87b1be000cb7388917 (do not edit this line) */
