/* Generated By:JJTree: Do not edit this line. ASTLogicalNOTExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public class ASTLogicalNOTExpression extends SimpleNode {
    public ASTLogicalNOTExpression(int id) {
        super(id);
    }

    public ASTLogicalNOTExpression(CParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=b593d816cf77fe021a95e7b402457650 (do not edit this line) */
