/* Generated By:JJTree: Do not edit this line. ASTSpecifierQualifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public class ASTSpecifierQualifierList extends SimpleNode {
    public ASTSpecifierQualifierList(int id) {
        super(id);
    }

    public ASTSpecifierQualifierList(CParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=7ad675e8455cfdec5e517e92ff38f23e (do not edit this line) */
