/* Generated By:JJTree: Do not edit this line. ASTStructOrUnionSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTStructOrUnionSpecifier extends SimpleNode {
  public ASTStructOrUnionSpecifier(int id) {
    super(id);
  }

  public ASTStructOrUnionSpecifier(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=9d25785afc33faae9460a9b66e719329 (do not edit this line) */
