/* Generated By:JJTree: Do not edit this line. ASTStructDeclaratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTStructDeclaratorList extends SimpleNode {
  public ASTStructDeclaratorList(int id) {
    super(id);
  }

  public ASTStructDeclaratorList(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=4342211b1cfd18c25b505852b01d9ce2 (do not edit this line) */
