/* Generated By:JJTree: Do not edit this line. ASTTypeSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTTypeSpecifier extends SimpleNode {
  public ASTTypeSpecifier(int id) {
    super(id);
  }

  public ASTTypeSpecifier(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=a94a2d51402bd0ab88b6392bba29cf33 (do not edit this line) */
