/* Generated By:JJTree: Do not edit this line. ASTTypedefName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public
class ASTTypedefName extends SimpleNode {
  public ASTTypedefName(int id) {
    super(id);
  }

  public ASTTypedefName(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(CParserVisitor visitor) {
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=447f5efc653b3e897d9410ab2ebe780f (do not edit this line) */
