/* Generated By:JJTree: Do not edit this line. ASTTypeName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.iguanatool.testobject.cparser;

public class ASTTypeName extends SimpleNode {
    public ASTTypeName(int id) {
        super(id);
    }

    public ASTTypeName(CParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public void jjtAccept(CParserVisitor visitor) {
        visitor.visit(this);
    }
}
/* JavaCC - OriginalChecksum=447df85ec482b3f66f5dbdf8ad6883b2 (do not edit this line) */
