/* Generated By:JavaCC: Do not edit this line. CParserTreeConstants.java Version 5.0 */
package org.iguanatool.testobject.cparser;

public interface CParserTreeConstants {
    int JJTPARSEUNIT = 0;
    int JJTEXTERNALDECLARATION = 1;
    int JJTFUNCTIONDEFINITION = 2;
    int JJTDECLARATION = 3;
    int JJTDECLARATIONLIST = 4;
    int JJTDECLARATIONSPECIFIERS = 5;
    int JJTSTORAGECLASSSPECIFIER = 6;
    int JJTTYPESPECIFIER = 7;
    int JJTTYPEQUALIFIER = 8;
    int JJTSTRUCTORUNIONSPECIFIER = 9;
    int JJTSTRUCTORUNION = 10;
    int JJTSTRUCTDECLARATIONLIST = 11;
    int JJTINITDECLARATORLIST = 12;
    int JJTINITDECLARATOR = 13;
    int JJTSTRUCTDECLARATION = 14;
    int JJTSPECIFIERQUALIFIERLIST = 15;
    int JJTSTRUCTDECLARATORLIST = 16;
    int JJTSTRUCTDECLARATOR = 17;
    int JJTENUMSPECIFIER = 18;
    int JJTENUMERATORLIST = 19;
    int JJTENUMERATOR = 20;
    int JJTDECLARATOR = 21;
    int JJTDIRECTDECLARATOR = 22;
    int JJTPOINTER = 23;
    int JJTTYPEQUALIFIERLIST = 24;
    int JJTPARAMETERTYPELIST = 25;
    int JJTPARAMETERLIST = 26;
    int JJTPARAMETERDECLARATION = 27;
    int JJTIDENTIFIERLIST = 28;
    int JJTINITIALIZER = 29;
    int JJTINITIALIZERLIST = 30;
    int JJTTYPENAME = 31;
    int JJTABSTRACTDECLARATOR = 32;
    int JJTDIRECTABSTRACTDECLARATOR = 33;
    int JJTTYPEDEFNAME = 34;
    int JJTSTATEMENT = 35;
    int JJTIDENTIFIERSTATEMENT = 36;
    int JJTCASESTATEMENT = 37;
    int JJTCASEEXPRESSION = 38;
    int JJTDEFAULTSTATEMENT = 39;
    int JJTEXPRESSIONSTATEMENT = 40;
    int JJTCOMPOUNDSTATEMENT = 41;
    int JJTSTATEMENTLIST = 42;
    int JJTIFSTATEMENT = 43;
    int JJTSWITCHSTATEMENT = 44;
    int JJTSWITCHEXPRESSION = 45;
    int JJTWHILESTATEMENT = 46;
    int JJTDOSTATEMENT = 47;
    int JJTFORSTATEMENT = 48;
    int JJTGOTOSTATEMENT = 49;
    int JJTCONTINUESTATEMENT = 50;
    int JJTBREAKSTATEMENT = 51;
    int JJTRETURNSTATEMENT = 52;
    int JJTBRANCHINGEXPRESSION = 53;
    int JJTEXPRESSION = 54;
    int JJTASSIGNMENTEXPRESSION = 55;
    int JJTASSIGNMENTOPERATOR = 56;
    int JJTCONDITIONALEXPRESSION = 57;
    int JJTCONSTANTEXPRESSION = 58;
    int JJTLOGICALOREXPRESSION = 59;
    int JJTLOGICALANDEXPRESSION = 60;
    int JJTINCLUSIVEOREXPRESSION = 61;
    int JJTEXCLUSIVEOREXPRESSION = 62;
    int JJTANDEXPRESSION = 63;
    int JJTRELATIONALEXPRESSION = 64;
    int JJTRELATIONALOPERATOR = 65;
    int JJTSHIFTEXPRESSION = 66;
    int JJTADDITIVEEXPRESSION = 67;
    int JJTMULTIPLICATIVEEXPRESSION = 68;
    int JJTCASTEXPRESSION = 69;
    int JJTUNARYEXPRESSION = 70;
    int JJTUNARYOPERATOR = 71;
    int JJTLOGICALNOTEXPRESSION = 72;
    int JJTPOSTFIXEXPRESSION = 73;
    int JJTPRIMARYEXPRESSION = 74;
    int JJTARGUMENTEXPRESSIONLIST = 75;
    int JJTCONSTANT = 76;


    String[] jjtNodeName = {
            "ParseUnit",
            "ExternalDeclaration",
            "FunctionDefinition",
            "Declaration",
            "DeclarationList",
            "DeclarationSpecifiers",
            "StorageClassSpecifier",
            "TypeSpecifier",
            "TypeQualifier",
            "StructOrUnionSpecifier",
            "StructOrUnion",
            "StructDeclarationList",
            "InitDeclaratorList",
            "InitDeclarator",
            "StructDeclaration",
            "SpecifierQualifierList",
            "StructDeclaratorList",
            "StructDeclarator",
            "EnumSpecifier",
            "EnumeratorList",
            "Enumerator",
            "Declarator",
            "DirectDeclarator",
            "Pointer",
            "TypeQualifierList",
            "ParameterTypeList",
            "ParameterList",
            "ParameterDeclaration",
            "IdentifierList",
            "Initializer",
            "InitializerList",
            "TypeName",
            "AbstractDeclarator",
            "DirectAbstractDeclarator",
            "TypedefName",
            "Statement",
            "IdentifierStatement",
            "CaseStatement",
            "CaseExpression",
            "DefaultStatement",
            "ExpressionStatement",
            "CompoundStatement",
            "StatementList",
            "IfStatement",
            "SwitchStatement",
            "SwitchExpression",
            "WhileStatement",
            "DoStatement",
            "ForStatement",
            "GotoStatement",
            "ContinueStatement",
            "BreakStatement",
            "ReturnStatement",
            "BranchingExpression",
            "Expression",
            "AssignmentExpression",
            "AssignmentOperator",
            "ConditionalExpression",
            "ConstantExpression",
            "LogicalORExpression",
            "LogicalANDExpression",
            "InclusiveORExpression",
            "ExclusiveORExpression",
            "ANDExpression",
            "RelationalExpression",
            "RelationalOperator",
            "ShiftExpression",
            "AdditiveExpression",
            "MultiplicativeExpression",
            "CastExpression",
            "UnaryExpression",
            "UnaryOperator",
            "LogicalNOTExpression",
            "PostfixExpression",
            "PrimaryExpression",
            "ArgumentExpressionList",
            "Constant",
    };
}
/* JavaCC - OriginalChecksum=482d7c5c14ddd733c4fdd560d671cff2 (do not edit this line) */
