/* Generated By:JavaCC: Do not edit this line. CParserTreeConstants.java Version 5.0 */
package org.iguanatool.testobject.cparser;

public interface CParserTreeConstants
{
  public int JJTPARSEUNIT = 0;
  public int JJTEXTERNALDECLARATION = 1;
  public int JJTFUNCTIONDEFINITION = 2;
  public int JJTDECLARATION = 3;
  public int JJTDECLARATIONLIST = 4;
  public int JJTDECLARATIONSPECIFIERS = 5;
  public int JJTSTORAGECLASSSPECIFIER = 6;
  public int JJTTYPESPECIFIER = 7;
  public int JJTTYPEQUALIFIER = 8;
  public int JJTSTRUCTORUNIONSPECIFIER = 9;
  public int JJTSTRUCTORUNION = 10;
  public int JJTSTRUCTDECLARATIONLIST = 11;
  public int JJTINITDECLARATORLIST = 12;
  public int JJTINITDECLARATOR = 13;
  public int JJTSTRUCTDECLARATION = 14;
  public int JJTSPECIFIERQUALIFIERLIST = 15;
  public int JJTSTRUCTDECLARATORLIST = 16;
  public int JJTSTRUCTDECLARATOR = 17;
  public int JJTENUMSPECIFIER = 18;
  public int JJTENUMERATORLIST = 19;
  public int JJTENUMERATOR = 20;
  public int JJTDECLARATOR = 21;
  public int JJTDIRECTDECLARATOR = 22;
  public int JJTPOINTER = 23;
  public int JJTTYPEQUALIFIERLIST = 24;
  public int JJTPARAMETERTYPELIST = 25;
  public int JJTPARAMETERLIST = 26;
  public int JJTPARAMETERDECLARATION = 27;
  public int JJTIDENTIFIERLIST = 28;
  public int JJTINITIALIZER = 29;
  public int JJTINITIALIZERLIST = 30;
  public int JJTTYPENAME = 31;
  public int JJTABSTRACTDECLARATOR = 32;
  public int JJTDIRECTABSTRACTDECLARATOR = 33;
  public int JJTTYPEDEFNAME = 34;
  public int JJTSTATEMENT = 35;
  public int JJTIDENTIFIERSTATEMENT = 36;
  public int JJTCASESTATEMENT = 37;
  public int JJTCASEEXPRESSION = 38;
  public int JJTDEFAULTSTATEMENT = 39;
  public int JJTEXPRESSIONSTATEMENT = 40;
  public int JJTCOMPOUNDSTATEMENT = 41;
  public int JJTSTATEMENTLIST = 42;
  public int JJTIFSTATEMENT = 43;
  public int JJTSWITCHSTATEMENT = 44;
  public int JJTSWITCHEXPRESSION = 45;
  public int JJTWHILESTATEMENT = 46;
  public int JJTDOSTATEMENT = 47;
  public int JJTFORSTATEMENT = 48;
  public int JJTGOTOSTATEMENT = 49;
  public int JJTCONTINUESTATEMENT = 50;
  public int JJTBREAKSTATEMENT = 51;
  public int JJTRETURNSTATEMENT = 52;
  public int JJTBRANCHINGEXPRESSION = 53;
  public int JJTEXPRESSION = 54;
  public int JJTASSIGNMENTEXPRESSION = 55;
  public int JJTASSIGNMENTOPERATOR = 56;
  public int JJTCONDITIONALEXPRESSION = 57;
  public int JJTCONSTANTEXPRESSION = 58;
  public int JJTLOGICALOREXPRESSION = 59;
  public int JJTLOGICALANDEXPRESSION = 60;
  public int JJTINCLUSIVEOREXPRESSION = 61;
  public int JJTEXCLUSIVEOREXPRESSION = 62;
  public int JJTANDEXPRESSION = 63;
  public int JJTRELATIONALEXPRESSION = 64;
  public int JJTRELATIONALOPERATOR = 65;
  public int JJTSHIFTEXPRESSION = 66;
  public int JJTADDITIVEEXPRESSION = 67;
  public int JJTMULTIPLICATIVEEXPRESSION = 68;
  public int JJTCASTEXPRESSION = 69;
  public int JJTUNARYEXPRESSION = 70;
  public int JJTUNARYOPERATOR = 71;
  public int JJTLOGICALNOTEXPRESSION = 72;
  public int JJTPOSTFIXEXPRESSION = 73;
  public int JJTPRIMARYEXPRESSION = 74;
  public int JJTARGUMENTEXPRESSIONLIST = 75;
  public int JJTCONSTANT = 76;


  public String[] jjtNodeName = {
    "ParseUnit",
    "ExternalDeclaration",
    "FunctionDefinition",
    "Declaration",
    "DeclarationList",
    "DeclarationSpecifiers",
    "StorageClassSpecifier",
    "TypeSpecifier",
    "TypeQualifier",
    "StructOrUnionSpecifier",
    "StructOrUnion",
    "StructDeclarationList",
    "InitDeclaratorList",
    "InitDeclarator",
    "StructDeclaration",
    "SpecifierQualifierList",
    "StructDeclaratorList",
    "StructDeclarator",
    "EnumSpecifier",
    "EnumeratorList",
    "Enumerator",
    "Declarator",
    "DirectDeclarator",
    "Pointer",
    "TypeQualifierList",
    "ParameterTypeList",
    "ParameterList",
    "ParameterDeclaration",
    "IdentifierList",
    "Initializer",
    "InitializerList",
    "TypeName",
    "AbstractDeclarator",
    "DirectAbstractDeclarator",
    "TypedefName",
    "Statement",
    "IdentifierStatement",
    "CaseStatement",
    "CaseExpression",
    "DefaultStatement",
    "ExpressionStatement",
    "CompoundStatement",
    "StatementList",
    "IfStatement",
    "SwitchStatement",
    "SwitchExpression",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "GotoStatement",
    "ContinueStatement",
    "BreakStatement",
    "ReturnStatement",
    "BranchingExpression",
    "Expression",
    "AssignmentExpression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConstantExpression",
    "LogicalORExpression",
    "LogicalANDExpression",
    "InclusiveORExpression",
    "ExclusiveORExpression",
    "ANDExpression",
    "RelationalExpression",
    "RelationalOperator",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "CastExpression",
    "UnaryExpression",
    "UnaryOperator",
    "LogicalNOTExpression",
    "PostfixExpression",
    "PrimaryExpression",
    "ArgumentExpressionList",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=482d7c5c14ddd733c4fdd560d671cff2 (do not edit this line) */
