/* Generated By:JavaCC: Do not edit this line. CParserVisitor.java Version 5.0 */
package org.iguanatool.testobject.cparser;

public interface CParserVisitor {
    void visit(SimpleNode node);

    void visit(ASTParseUnit node);

    void visit(ASTExternalDeclaration node);

    void visit(ASTFunctionDefinition node);

    void visit(ASTDeclaration node);

    void visit(ASTDeclarationList node);

    void visit(ASTDeclarationSpecifiers node);

    void visit(ASTStorageClassSpecifier node);

    void visit(ASTTypeSpecifier node);

    void visit(ASTTypeQualifier node);

    void visit(ASTStructOrUnionSpecifier node);

    void visit(ASTStructOrUnion node);

    void visit(ASTStructDeclarationList node);

    void visit(ASTInitDeclaratorList node);

    void visit(ASTInitDeclarator node);

    void visit(ASTStructDeclaration node);

    void visit(ASTSpecifierQualifierList node);

    void visit(ASTStructDeclaratorList node);

    void visit(ASTStructDeclarator node);

    void visit(ASTEnumSpecifier node);

    void visit(ASTEnumeratorList node);

    void visit(ASTEnumerator node);

    void visit(ASTDeclarator node);

    void visit(ASTDirectDeclarator node);

    void visit(ASTPointer node);

    void visit(ASTTypeQualifierList node);

    void visit(ASTParameterTypeList node);

    void visit(ASTParameterList node);

    void visit(ASTParameterDeclaration node);

    void visit(ASTIdentifierList node);

    void visit(ASTInitializer node);

    void visit(ASTInitializerList node);

    void visit(ASTTypeName node);

    void visit(ASTAbstractDeclarator node);

    void visit(ASTDirectAbstractDeclarator node);

    void visit(ASTTypedefName node);

    void visit(ASTStatement node);

    void visit(ASTIdentifierStatement node);

    void visit(ASTCaseStatement node);

    void visit(ASTCaseExpression node);

    void visit(ASTDefaultStatement node);

    void visit(ASTExpressionStatement node);

    void visit(ASTCompoundStatement node);

    void visit(ASTStatementList node);

    void visit(ASTIfStatement node);

    void visit(ASTSwitchStatement node);

    void visit(ASTSwitchExpression node);

    void visit(ASTWhileStatement node);

    void visit(ASTDoStatement node);

    void visit(ASTForStatement node);

    void visit(ASTGotoStatement node);

    void visit(ASTContinueStatement node);

    void visit(ASTBreakStatement node);

    void visit(ASTReturnStatement node);

    void visit(ASTBranchingExpression node);

    void visit(ASTExpression node);

    void visit(ASTAssignmentExpression node);

    void visit(ASTAssignmentOperator node);

    void visit(ASTConditionalExpression node);

    void visit(ASTConstantExpression node);

    void visit(ASTLogicalORExpression node);

    void visit(ASTLogicalANDExpression node);

    void visit(ASTInclusiveORExpression node);

    void visit(ASTExclusiveORExpression node);

    void visit(ASTANDExpression node);

    void visit(ASTRelationalExpression node);

    void visit(ASTRelationalOperator node);

    void visit(ASTShiftExpression node);

    void visit(ASTAdditiveExpression node);

    void visit(ASTMultiplicativeExpression node);

    void visit(ASTCastExpression node);

    void visit(ASTUnaryExpression node);

    void visit(ASTUnaryOperator node);

    void visit(ASTLogicalNOTExpression node);

    void visit(ASTPostfixExpression node);

    void visit(ASTPrimaryExpression node);

    void visit(ASTArgumentExpressionList node);

    void visit(ASTConstant node);
}
/* JavaCC - OriginalChecksum=e7f7d225f0574848903f6644844f7cd8 (do not edit this line) */
